#!/usr/bin/env node
/**
 * Eski "Modül N" issue'larını, yeni modül kodlu karşılıklarına işaret eden
 * bir yorum bırakarak kapatır. Kapsam kaybolmaz; iz sürülebilir kalır.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const state = JSON.parse(fs.readFileSync(path.join(__dirname, 'created.json'), 'utf8'));
const REPO = process.env.REPO || 'rtosma/YAKITTAKIPSISTEMI';
const TOKEN = process.env.GH_TOKEN || process.env.GITHUB_TOKEN;
const DRY = process.argv.includes('--dry-run');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const ref = (key) => (state[key] ? `#${state[key]} \`${key}\`` : `\`${key}\``);

// Eski issue → yeni modül kodları eşlemesi
const MAP = {
  2:  { title: 'Modül 1: Çekirdek Kurulum ve Güvenlik', keys: ['ARCH-100', 'ARCH-101', 'AUTH-201', 'AUTH-202', 'RES-901', 'RES-902', 'OPS-1101'] },
  3:  { title: 'Modül 2: React Context’ten Zustand’a Geçiş', keys: ['FE-800', 'FE-801', 'FE-802'] },
  4:  { title: 'Modül 3: Mock Veri Altyapısından REST API’ye Geçiş', keys: ['ARCH-100', 'ARCH-104', 'FE-800', 'FE-802', 'DOC-1201'] },
  5:  { title: 'Modül 4: Gerçek Zamanlı Telemetri (MQTT / WebSocket)', keys: ['IOT-301', 'IOT-302', 'ARCH-103', 'FE-801'] },
  6:  { title: 'Modül 5: Test ve Pipeline Kurulumu (CI/CD)', keys: ['TEST-1006', 'TEST-1001', 'TEST-1004', 'OPS-1102', 'OPS-1103'] },
  7:  { title: 'Modül 6: Personel İzin Takip Sistemi', keys: ['HR-1801'] },
  8:  { title: 'Modül 7: Araç Muayene, Periyodik Bakım ve Lastik Takip', keys: ['FLEET-1408', 'FLEET-1407', 'FLEET-1409'] },
  9:  { title: 'Modül 8: GİB Uyumlu E-İrsaliye Entegrasyonu', keys: ['COMP-601', 'COMP-602', 'COMP-603', 'COMP-604', 'COMP-605'] },
  10: { title: 'Modül 9: Şantiye Laboratuvar ve Numune Takibi', keys: ['INV-1507'] },
  11: { title: 'Modül 10: Envanter ve Yedek Parça Stok Takibi', keys: ['INV-1506'] },
  12: { title: 'Modül 11: AI Destekli Aylık Yönetim Raporu', keys: ['REP-724', 'AI-502'] },
};

async function gh(method, endpoint, body) {
  const args = ['-sS', '-X', method, '-w', '\n%{http_code}',
    '-H', `Authorization: Bearer ${TOKEN}`,
    '-H', 'Accept: application/vnd.github+json',
    '-H', 'Content-Type: application/json',
    '-H', 'User-Agent: yakit-roadmap-sync'];
  let tmp;
  if (body) {
    tmp = path.join(os.tmpdir(), `gh-${Date.now()}-${Math.random().toString(36).slice(2)}.json`);
    fs.writeFileSync(tmp, JSON.stringify(body));
    args.push('--data-binary', `@${tmp}`);
  }
  args.push(`https://api.github.com${endpoint}`);
  const out = await new Promise((res, rej) =>
    execFile('curl', args, { maxBuffer: 16 * 1024 * 1024 }, (e, so, se) => (e && !so ? rej(new Error(se || e.message)) : res(so))));
  if (tmp) fs.unlinkSync(tmp);
  const i = out.lastIndexOf('\n');
  const status = Number(out.slice(i + 1).trim());
  if (status < 200 || status >= 300) throw new Error(`${method} ${endpoint} → ${status}: ${out.slice(0, 300)}`);
  return out.slice(0, i);
}

for (const [num, { title, keys }] of Object.entries(MAP)) {
  const list = keys.map((k) => `- ${ref(k)}`).join('\n');
  const body = [
    '## 🔄 Bu issue yeni modül kodlu iş paketlerine taşındı',
    '',
    `**${title}** kapsamı, \`ISSUES_ROADMAP.md\` (Node.js Enterprise Roadmap v2.2) numaralandırmasına göre yeniden bölündü.`,
    'Hiçbir kapsam düşürülmedi; iş, aşağıdaki issue’larda daha küçük ve ölçülebilir parçalar hâlinde takip edilecek:',
    '',
    list,
    '',
    'Tüm iş paketleri artık `mod:*`, `layer:*`, `P0-P3`, `size:*` etiketleri ve FAZ milestone’ları ile izleniyor.',
    'Ayrıntı için: `docs/ISSUES_ROADMAP.md` ve `docs/PROJE-REHBERI.md`.',
    '',
    'Bu issue, mükerrer takibi önlemek için kapatılmıştır.',
    '',
    '---',
    '_Generated by [Claude Code](https://claude.ai/code)_',
  ].join('\n');

  if (DRY) { console.log(`#${num} → ${keys.join(', ')}`); continue; }
  await gh('POST', `/repos/${REPO}/issues/${num}/comments`, { body });
  await sleep(600);
  await gh('PATCH', `/repos/${REPO}/issues/${num}`, { state: 'closed', state_reason: 'not_planned' });
  console.log(`  ✔ #${num} kapatıldı → ${keys.length} yeni issue`);
  await sleep(600);
}
console.log('🏁 Eski issue’lar kapatıldı.');
